[package]
name = "rifts-settings"
version = "0.1.0"
edition = "2021"
authors = ["lbgos <285507185+lbgos@users.noreply.github.com>"]

[features]
custom-protocol = ["tauri/custom-protocol"]

[build-dependencies]
tauri-build = { version = "2", features = [] }
cc = "1"

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
tungstenite = "0.28"

[profile.release]
strip = true
codegen-units = 4
